CREATE TABLE IF NOT EXISTS accounts
(
    ulid      VARCHAR(26) NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    id        BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users
(
    ulid       VARCHAR(26)  NOT NULL UNIQUE,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    CONSTRAINT fk_users_account_id FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE,
    account_id BIGINT       NOT NULL,
    id         BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
