// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Namespace struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Account *Account `json:"account"`
}

type NewAccount struct {
	Name string `json:"name"`
}

type NewNamespace struct {
	Name string `json:"name"`
}

type NewStack struct {
	Name        string `json:"name"`
	NamespaceID string `json:"namespaceId"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Query struct {
}

type Stack struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Namespace *Namespace `json:"namespace"`
	Account   *Account   `json:"account"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
